name: CI build and deploy aws

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: CI build action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Replacing the jfrog repo password 
        run: |
          echo --- Replacing Jfrog password ${{secrets.JFROG_REPO_PASSWORD}} ---
          sed -i 's/put_your_password/${{secrets.JFROG_REPO_PASSWORD}}/g' MovieApplication/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build

      - name: Upload to Jfrog Repo
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs